### ISSUE TITLE
Adding directly to master bibliography (not antiquarian biographies)

### ISSUE THREAD

**Issue by stephencblair** [UCL/frrant#311] opened 2021-12-22 16:03 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, the only way to add a bibliographic item is to add it to one of the discrete bibliographies attached to individual antiquarians. (The master bibliography displays the combined contents of all the antiquarian bibliographies, but you can’t add to it directly.) The problem is that we have many items to add to the general bibliography which aren’t related only to one specific antiquarian, and there’s no way to insert them directly into the master bibliography.

**Describe the solution you'd like**
We would like to be able to add items directly into the master bibliography. Ideally, on the bibliography page, there could be an ‘add’ button just like the one currently displayed under the bibliography heading of an antiquarian’s page.

**Comment by rogerstafforducl** [comment] 2022-08-25 12:22
Duplicate of #323

**Comment by tcouch** [comment] 2022-09-22 21:01
Closing as it's a duplicate of #323

**Closed as completed by tcouch** 2022-09-22 21:01 UTC
