### ISSUE TITLE
Add columns to texts when editing

### ISSUE THREAD

**Issue by raquelalegre** [UCL/frrant#71] opened 2020-12-01 21:46 UTC
Rich text editor functionality should include writing in columns and tables.

@peterbispham has tested tables and they don't work well in the current editor we are using. Any other possible solutions?

**Comment by tcouch** [comment] 2021-11-05 15:40
To follow up with @rmamarshall (one solution might be to add multiple boxes side by side)

**Comment by raquelalegre** [comment] 2021-11-08 14:51
@rmamarshall do you know how many columns typically? Can we get away assuming there's 2 columns?

**Comment by rmamarshall** [comment] 2021-11-08 15:07
@raquel-ucl @tcouch As promised in the meeting on Friday, here is an example of the type of material for which we need this feature. In the attached example, there are five columns. Note, however, that in some rows, the final pair of columns is merged: a table feature might be the ideal solution, though I have no idea how feasible this is. 
I've been thinking about the suggested work-around (multiple text boxes): this could also work, but I presume the app. crit. would be discrete for each box, which would be a problem if we ended up with multiple notes relating to the same original text that shared the same app. crit. number.

![Jerome_Chron_Columns](https://user-images.githubusercontent.com/75932472/140764408-4ae993bc-8c5e-4b47-9c53-bda770c8779f.JPG)

**Comment by tcouch** [comment] 2022-09-13 19:24
I've added some information on how the rich text editor works here: https://github.com/UCL/frrant/wiki/Notes-on-FRRAnt-Rich-Text-Editor

**Comment by tcouch** [comment] 2022-09-13 19:29
There appear to be a few options to try:
* Quilljs version 2.0.0 includes a table module which may do the job. Development seems to have stopped though before an official release so it's not a sure bet and there may be breaking changes to existing functionality that we rely on.
* We can look for an alternative rich text editor. If we find one that provides everything we need, we'll have to convert all our mentions etc. to whatever format the new editor expects them to be in.
* A slightly hacky work around could be for users to enter tables in markdown format and convert these to html when we validate the form data. This breaks the WYSIWYG principle though and puts the burden of learning markdown tables on the user.
* There's also the multiple editors option proposed above, but I'm not a fan.

**Comment by acholyn** [comment] 2023-07-24 09:58
@rmamarshall Revisiting this - is it tables _and_ columns you'd like or is it mainly tables due to how you'd input the information? It _might_ be possible to include both if you want both for different uses, but the above example seems more along the lines of a table.

**Comment by rmamarshall** [comment] 2023-08-04 15:51
@acholyn Hi Amanda; the functionality described in 'Feature/text editor updates #401' seems to be an excellent fit for what we want. May I check whether any of the new features have already been implemented? I recently noticed that some of the alphabetum font characters in the symbol picker are no longer displaying correctly:

![image](https://github.com/UCL/frrant/assets/75932472/580017e2-99d1-4bd7-8c6a-5f3f913c60d5)

**Comment by acholyn** [comment] 2023-08-07 08:50
Hi @rmamarshall, the text editor updates haven't been applied to the pre-prod server just yet as they're awaiting a review but once they are, I can let you all know. In the meantime, if it would be helpful, I could record a demo of the changes so you have an idea of what to expect?

Regarding the missing characters, I'm not entirely sure why that is, but based on a quick check, it looks like the file which should have those symbols is not being found properly -- I'll see if it can be fixed soon

**Comment by rmamarshall** [comment] 2023-08-07 09:25
Hi @acholyn, a demo would be great, but only if it doesn't take too much of your time to put together! Is there anything else I can help with at the moment? Gradually getting back on top of things after birth of Imogen.

**Comment by acholyn** [comment] 2023-08-07 10:08
It's not urgent but regarding #166 - if you or @dgiordani could follow up, that should be fairly easy to implement and cross off the list :)
Otherwise I think we're all good until the review is done and I start on the next fixes/features

**Comment by rmamarshall** [comment] 2023-08-07 16:39
Hi @acholyn, just  a note to say thank you for the video - very impressive! On the subject of spacing between paragraphs, it would be best if there was none at all - the issue is that sometimes we have to enter lines of poetry, which look very peculiar with the additional spacing. If we need a line space between elements, we can add this manually using return.

**Comment by rmamarshall** [comment] 2023-08-07 16:42
@acholyn Just a quick check - do footnotes accept Greek and 'at' mentions to the bibliography? 

Also, does the table accept Greek and app. crit. notes when entering 'original text' in fragments / testimonia? From what you said in the video, app. crit. notes may not work, but this is really important requirement.

**Comment by acholyn** [comment] 2023-08-07 18:05
@rmamarshall The footnotes accept the Greek letters but not whilst the dialog is open (it prevents interaction outside the dialog currently). You can paste into the dialog and it will not seem to recognise it but when you submit it, it'll show up in the footnote content without issue. I'm not sure whether the mentions will work for the bibliography - certainly the current mention behaviour is not active in the footnote dialog (it currently uses your browser's built in dialog). My understanding was that the @ mentions were not needed in the footnotes as they were to be simple text. If they _are_ needed, I would either have to build a custom modal which effectively functions as another text editor or there might be a way to just copy in the contents of the mention from the main editor into the footnote (maybe by wrapping in @@ symbols? eg. in  the editor you get the @ mention for Lucius Accius, copy this text and paste it into the footnote content so that it says `@Lucius Accius/@` ?

Currently the app. crit notes are not available in the table as that slipped under my radar. From a quick look, it might be possible to tie in their functionality as it's based on listening for the `#` character. The Greek symbols are accepted. As mentioned above, I'd probably copy and paste into the dialog.
If that becomes too fiddly, I think I could make a simple modal which effectively acts the same (not an extra editor) but no longer limits your interaction on the page so you can more easily use the Greek (for the tables and the footnotes).

Whilst it's the wrong way round, I think the footnotes and tables work in the app. crit 😅

**Comment by rmamarshall** [comment] 2023-08-09 13:45
@acholyn Hi Amanda, if I understand correctly, input of Greek in footnotes and of Greek and app. crit. links in the tables could be simplified by a new modal / user interface. I think this would probably work best, as academic footnotes are often quite long and complex, and adding everything via the existing single floating line (or typing it out first and then pasting) would impede workflow.

If I follow the suggested work-around for 'at' mentions in the footnotes, one would first have to create the 'at' mention in the ordinary text box, then paste this to the footnotes with additional 'at' signs added. This seems very clunky, and could introduce lots of errors if the impromptu 'at' mentions were not immediately deleted or the additional 'at' signs were misplaced (I also worry about the editing stage when we might want to add footnotes to an existing body of text). 

Could the app. crit. text editor be used for the footnote editor? It seems this already has the desired functionality, plus gives us the ability to add / remove entries while retaining the correct numerical sequence.

**Comment by acholyn** [comment] 2023-08-09 13:55
I'll try out how the app. crit builder works, it may be simpler than I thought to include the text editor with its functionality in the modal

**Closed** 2023-10-06 15:38 UTC
Labels: Essential, Text editor, Time consuming, ResearchApproval
