### ISSUE TITLE
Add bibliography items directly to master bibliography

### ISSUE THREAD

**Issue by tcouch** [UCL/frrant#323] opened 2022-05-04 19:45 UTC
May we add an ability to add items of bibliography directly to the ‘Bibliography’ page, rather than through antiquarian entries? Some of the works we wish to cite relate to citing authors or are relevant for multiple entries (this is a very high priority).

**Comment by tcouch** [comment] 2022-05-26 19:53
After discussion at today's meeting we've now agreed that rather than being tied directly to a specific antiquarian, bibliography items should be independent in order to allow multiple Antiquarian pages to link to the same Bibliography item via @ mentions. As such we will:
* Add a "add bibliography item" link to /bibliography/list/
* Enable @mentions from Antiquarian pages to implicitly generate links to bibliography items

Questions
* Do we still want to display bibliography items on Antiquarian pages?
* Should this be a formal foreign key relationship?
* Or, can we generate information about which pages reference bibliography items as needed by parsing the relevant text fields?

**Comment by tcouch** [comment] 2022-05-26 20:23
The “cited here” column in the master bibliography would not take you to the citation place, but to a new view that lists all the @mentions in the same way Search results would. Perhaps directly link to the actual search page showing the results?

**Comment by rogerstafforducl** [comment] 2022-08-25 12:25
origionally requested in #311, which I marked as duplicate https://github.com/UCL/frrant/issues/311#issue-1086969643

**Comment by rogerstafforducl** [comment] 2022-09-08 12:43
Liszt:
- [x] Change Antiquarian - add field bibliography_items2, M2M to BibliographyItem 
- [x] Migrate, including populating the new intermediate M2M table from the old GR table _Done, but needs review - not sure that reverse would work_
- [x] Remove the GR (bibliography_items) from Antiquarian
- [x] Remove the GFK from BibliographyItem (2 fields + parent)
- [x] Rename bibliography_items2 to bibliography_items in Antiquarian
- [x] find all mentions of BibliographyItem.parent, as this no longer works
- [x] biblographitem_list.html contains `<a href={{ item.parent.get_absolute_url }}>Cited Here</a></div>`, which refers to BibliographyItem.parent, which is Antiquarian. Need to change this link to point to filtered AntiquarianListView as above
- [x] Make BibliographyDetailView including a post method for create and edit
- [x] make template for the BibliographyDetailView - there is bibliographyitem_form.html - maybe that does the job???
- [x] tests
- [ ] more tests

**Comment by rogerstafforducl** [comment] 2022-11-04 14:08
For associating bibliography item with citing author:
- [x] add a M2M on CitingAuthor to BibliographyItem, similar to that on Antiquarian
- [x] migrate that
- [x] add bibliography to citing author views (perhaps not all of them?
  - not needed on detail view
  - in fact, don't need to update any of the CA views
- alter templates as per views
  - [x] detail
  - [x] form - not needed
  - [ ] full list - not needed
  - [ ] list  - not needed
- [ ] could add "then add bibliography items" to botom of create citing author form template, but inclined not to, think it's not needed
- [x] add list of citing authors to bibliography views (create, update, view) 
- [x] and to templates
- [ ] think about what needs to be locked in bib views and citing author views
- [x] think about permissions in bib views and citing author views

Alternative strategy:
- add bibliography item to the list of "OriginalText" items, though I think bib items seem to be fundamentally different, so won't do that
-

**Comment by tcouch** [comment] 2023-01-11 12:49
An additional request from the research team: Can we create links to bibliography items automatically when referenced in @mentions? Look at DynamicTextField class to see if we can add something to parse the text for mentions on save.

**Comment by tcouch** [comment] 2023-01-12 09:54
@rmamarshall I've managed to put something in place which will automatically link bibliography items to an Antiquarian when an @mention is used in the introduction. There are a couple of questions that follow from this though:

1. Should bibliography items be unlinked if the @mention is later removed from the introduction?
2. If so, do you also want to be able to link bibliography items independently of @mentions in the introduction text?

If the answer to both those questions is yes, then we'd need to do some further work to track the source of the link so that we only remove those which came from @mentions if they are removed from the introduction.

On the other hand, if you're happy to treat the introduction as the sole source of truth for which bibliography items should be linked, that'd be much easier for us to set up - we'll be able to refresh the list of linked bibliography items by checking the introduction for all bibliography mentions each time it's saved.

**Comment by rmamarshall** [comment] 2023-01-13 15:15
@tcouch 
1. Yes, bibliogrpahy items should be linked / unlinked when an @mention is created or delted.
2. No, this will not be necessary.

Hope this makes it easier!

**Comment by tcouch** [comment] 2023-01-13 16:17
@rmamarshall Yes that's better. A final question then is how you'd like me to handle bibliography items which are currently linked to an Antiquarian, but are not mentioned in the Introduction? For example, quickly looking through Varro, I see two bibliography entries for E. Zingg [2019], but there's no mention in the actually introduction. On the other hand items like A. Mancini [1896] and H. Jagielski [1912] are clearly talked about in the Introduction, but aren't referenced using @mentions. If you want to keep these, @mentions for each of them would need to be added to the current text.

The simplest approach from my point of view would be for me to take all existing linked bibliography items and append them as a list of @mentions to the end of the Introduction. It'd then be up to you to move them to the appropriate place in the text later.

**Comment by rmamarshall** [comment] 2023-01-13 16:40
@tcouch 
I think the issue is a bit more complex - bibliographical items can also be cited in the commentaries to individual fragments, thus they appear in an antiquarian's bibliography but are not necessarily cited in the introduction: these should also be linked to antiquarians.
Some references were added before @mentions were enabled; it shouldn't be too difficult to cross-check these and add them to the master bibliography where necessary / update to @mentions.

**Comment by tcouch** [comment] 2023-01-16 10:30
@rmamarshall Ok, I've drawn a series of diagrams to illustrate this. In the first, the bibliography for Antiquarian A comprises five items: three from the introduction and two from linked fragment F1:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/5113832/212655420-586823fa-9f01-4f7f-8e3a-a8ebbaf07886.png">
In the second, fragment F2 is also linked to Antiquarian A, so the bibliography items from its commentary are also added to Antiquarian A's bibliography:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/5113832/212655811-aa59be02-b9b5-4e3b-82f3-ff8457a626da.png">
Then fragment F1 is also linked to Antiquarian B, so the bibliography items in its commentary also contribute to Antiquarian B's bibliography:
<img width="503" alt="image" src="https://user-images.githubusercontent.com/5113832/212656120-816ebbcf-3544-4f3d-b772-3aedeea810ff.png">
And finally, the link between fragment F1 and Antiquarian A is removed, so F1's bibliography items are removed from Antiquarian A's bibliography:
<img width="504" alt="image" src="https://user-images.githubusercontent.com/5113832/212656527-31d6d10f-436a-4e03-9ebc-1c171f259172.png">
Does that sound about right? Does what I've described also apply for linked Testimonia and Apposita?

**Comment by rmamarshall** [comment] 2023-01-24 09:16
@tcouch Hi Tom, 
Great diagrams - much easier to follow! I think the above captures what we want brilliantly; the same structure should be followed with Testimonia and Apposita.
To clarify one point: if e.g. b4 also appeared in BOTH Antiquarian A Introduction AND Fragment F1 commentary, but the link between F1 and antiquarian A1 was removed, b4 should still appear in Bibliography A (by reason of still appearing in Antiquarian A Introduction). Hope that makes sense.

**Comment by rogerstafforducl** [comment] 2023-03-10 11:38
@tcouch @rmamarshall Using the strategy outlined above, it seems to me that it is possible to orphan bibliography items. If all @mentions for a bibliography item are removed from introductions and commentaries, then the bibliography will be unassociated with any other object. Is this OK?

**Comment by rmamarshall** [comment] 2023-03-13 09:20
@tcouch @rogerstafforducl If all @mentions are deleted, there should be a warning message with an option to delete the item from the bibliography as well. This should not happen automatically, as it may be that an @mention is deleted in the course of editing an entry with the intention of moving it elsewere.

**Comment by rogerstafforducl** [comment] 2023-03-13 09:45
@rmamarshall @tcouch The other side of the coin is, I think, that if a bibliography item, or any other @mentionable item is itself deleted, we don't, as far as I see, have a way to remove or warn of any resultant dead links in text items. If I were to delete a bibligraphy item that were already @mentioned in an introduction, the @mention would remain, but would be a dead link (not sure how dead mentions are handled currently - will have a look on Friday).

**Comment by tcouch** [comment] 2023-03-14 11:08
@rogerstafforducl perhaps setting on_delete=models.PROTECT on the m2m relationship would be a good idea? On the UI we could do something like disabling the delete button on the bibliography item detail page when it has 1 or more links. A tooltip could explain that the links need to be removed before the bibliography item can be deleted.

**Closed as completed** 2023-07-20 14:54 UTC
Labels: Essential
